version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.5-jessie
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes npm upx-ucl
      - run: npm install -g n yarn
      - run: n latest
      - run: yarn install
      - run: yarn flow
      - run: ./build.sh
      - run: ./slow-tests.sh
